### ISSUE TITLE
Log In problem 

### ISSUE THREAD

**Issue by PsyhoPaat** [Fundryi/Destiny#1]
Problem Description:  Internal Exception: java.lang.IllegalStateException: Could not determine owner for the override on simpleoregen:endcopperore. Value: Block{null}

**Comment by Fundryi** [comment]
I need more info. I can't tell if it's on a Server or Singleplayer. Or it happens after you place a specific block or not. Give me more information, please.

**Comment by PsyhoPaat** [comment]
it's just on a server and I get this when I try to join in on the server 

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PsyhoPaat** [comment]
and In the log it shows all of the items of simpeloregen

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Fundryi** [comment]
I can't help you if you don't help me.
Write specific information like.
I can't join the Official server/ or I can't join my Own server.
Or It happened after I added that block into my RS system Or My server kicked me after I place a "diamond" Block there. 

You give me no information at all. How should I help you then?
My guess is Reinstall the server completely if it is your own server. Maybe reset the world too. after that everything should work fine. Besides that, if you place/made any changes in the game that kicked you after that. Don't do it again.

**Comment by hilerjm** [comment]
Hello Fundryi, I know this issue is closed however my friend PsyhoPaat told me he was having this issue.
The issue happens when he is connecting to my server at the ip dlcincluded.com.
We were on version 0.4.2, and the issue happened upon his FIRST attempts at logging in. He has / had no player data on the server to delete. 7 other players have been able to join with NO issues so it was not a server issue.

The issue has something to do with SimpleOreGen in one of the mods. We are unsure as to what caused it. We tried uninstalling the pack, and reinstalling. Reinstalling twitch launcher, installing the pack manually with multiMC gave the same error. Same with downloading minecraft, installing forge, and adding the mods and config folders directly from a working copy on a different computer. 

We had to completely uninstall java, twitch, and every file from everything previously.

With a fresh install of java, twitch, and the 0.4.2 version of the pack, he got a different error(can't remember off the top of my head) but it was pointing to an AV software blocking the connection. 

Just wanted to let you know so if you see the issue in the future you can attempt a work around that might actually work. 

Thanks and have an awesome day, Ty for the awesome pack

**Comment by Fundryi** [comment]
Thank you for the info. :)
