### ISSUE TITLE
Dimension Change Issue

### ISSUE THREAD

**Issue by jezzen** [Fundryi/Destiny#6]
Hopefully, you're still active on this modpack.

For some reason, when I go to another dimension (The End, Utility Worlds' Mining Dimension and the Nether via Draconic Evolution's Dislocator) I get stuck with the loading screen while (usually) the game continues on in the background (noticeable by weather, block and mob sounds)

![2017-11-15_15 00 12](https://user-images.githubusercontent.com/18730266/32827264-4be89956-ca37-11e7-807f-9cc5a7e67655.png)

Considering how the nether was unaffected, I guessed that some gui or event occurred that prevents the loading screen from going away while keeping the game playing (I'm on SSP, and would expect the game to be paused or frozen in such circumstances). I used the Draconic Evolution Dislocator to transport between the nether and overworld, and the issue is there again.

Here's one of the log files of when this occurs (no crash-log because no crash)
[latest.log](https://github.com/Fundryi/Destiny/files/1473959/latest.log)

With
[time] [main/INFO]: [CHAT] You got: item
as a placemarker of my actions (via Gift of the Gods) starting at line 10498, I (starting in the Nether) went back to the Overworld, to and from the Nether again, then tried to go into the Mining World (Utility Worlds)

In the log, I can't find any noticeable errors that might refer to this between when I head to the Mining World (line 10701) and I close the game (line 10752).

I don't know if others have come across this issue or what, as there is no mention of it in the comments or issues, and those are a couple months old.

**Comment by Fundryi** [comment]
Im here and working on it again, but not 100% active. I will look into your problem. I just want to let u know that If I find a solution I will write it here :) 
I'm currently working on a "Big" updated because so many mods got updated and bug fixes etc.
Soo it will take a bit to get it "Stable" currently I have a "Memory" leak problem with one of the mods -.-

**Comment by jezzen** [comment]
Nice, I'll be looking forward to it. I previously had I crashing problem where I removed Dynamic Surroundings based on one of the comments and it stopped having issues afterwards (not sure how they worked it out, as mine suddenly crashed leaving no crash log or saving the world).

I like the proper keybind configs which most packs seem to ignore and the mod integration and balancing.

A couple things you may want to look at:

**Comment by Fundryi** [comment]
Thanks for all the feedback.

- Will get a harder Recipe, but I mostly didn't change the most Recipes yet because I waited for Avaritia Mod.
- I didn't even know that such an Items is in the pack lol Thanks for the info :P 
- Makes sense I know it is cheap and you can exploit, but it's only because Avaritia is not yet here :/ I will just blacklist it on the Uncrafting Table.
- I will add some items to the blacklist if you know items that can be exploited pls list them below because I don't remember any cuz the last time I played the modpack was about 4-5 Months :P 

Thanks for the feedback and all I was going even to add Quest Book, but I just don't have the time for it.

**Comment by jezzen** [comment]
Narrowed it down to Universal Remote via adding/removing mods (Thank god for binary search). Checking their issues, I found to [relevant post](https://github.com/orbwoi/UniversalRemote/issues/4) and it's already been fixed. Now to actually do some progression in the pack without the scare of needing to restart (I hadn't even gotten the Philosophers' Stone in that save). I'm starting another one from scratch to avoid skipping progression, taking shortcuts, getting OP equipment (Dev blade, gem armor, draconic armor...), etc. Already got a nice portion of riverside surrounded by a half-built wall (the cobble grind without the condenser... I decided to restrict myself from it until after I get the Philosophers Stone but available before the transmutation table)

**Comment by Fundryi** [comment]
Before you start a new world, you should wait for the updated that will come soon. I don't think its compatible with the old worlds because so many mods updated have been pushed out.
The Updated should be out tomorrow OR maybe today, its still much work, and it will be BETA so might be not that stable.

**Comment by jezzen** [comment]
Looking forward to the new stuff. As for the new generation, I'll have a think about it, as I could keep my current world and leave the rest to new chunks (I haven't gone far from spawn), delete current chunks apart from where the base is, or use world edit to move it over. Either way I like what I currently have going.

![2017-11-18_20 31 24](https://user-images.githubusercontent.com/18730266/32979408-6860884e-cca0-11e7-85ea-263d44e2049c.png)

**Comment by Fundryi** [comment]
Looks cool, just wanna tell u that Im not gonna finish the updated in time sadly, I ran into more issues and need to fix them first.

**Comment by jezzen** [comment]
That's fine, probably worth the wait. Let me know if you need any brainstorming for solutions, and if so probably doing a new issue thread for it instead of continuing this one
